/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class x10_x10rt_MessageHandlers */

#ifndef _Included_x10_x10rt_MessageHandlers
#define _Included_x10_x10rt_MessageHandlers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     x10_x10rt_MessageHandlers
 * Method:    registerHandlers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_x10_x10rt_MessageHandlers_registerHandlers
  (JNIEnv *, jclass);

/*
 * Class:     x10_x10rt_MessageHandlers
 * Method:    sendMessage
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_x10_x10rt_MessageHandlers_sendMessage
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
